sudo: required

language: java

jdk:
   - openjdk11

before_install:
   - openssl aes-256-cbc -K $encrypted_7f8420691ff5_key -iv $encrypted_7f8420691ff5_iv
      -in ./travis/helseci.key.enc -out ./travis/helseci.key -d
   - git clone https://github.com/navikt/github-apps-support.git
   - export PATH=`pwd`/github-apps-support/bin:$PATH
   - export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
      $GITHUB_APP_ID`)
   - export COMMIT_SHORT=$(git rev-parse --short HEAD)
   - export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
   - echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
   - rm "${JAVA_HOME}/lib/security/cacerts"
   - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

script:
   - "./gradlew check"
   - "./gradlew build"
   - |
      if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then

        git config user.name team-helse[bot]
        git config user.email team-helse[bot]@users.noreply.github.com

        # TODO upload to bintray?

        awk '($1=="version" && $3 ~ /[0-9]+/){$3=$3+1} 1' build.gradle.kts > build.gradle.new && mv build.gradle.new build.gradle.kts
        git add build.gradle.kts
        git commit -m "Bump version" -m "Caused by $TRAVIS_BUILD_WEB_URL" --author "$ORIGINAL_COMMITTER"

        git push https://x-access-token:$GH_TOKEN@github.com/navikt/helse-streams.git master

      fi

before_cache:
   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
   directories:
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
env:
   global:
      - GITHUB_APP_ID=19726
      - secure: SBrY0OwacFrVazvIqjDvqCohavx5cXT/ioKIdIm/tX40XCZJiJkBmuRI1ONNYVKrz+cUD/NYS+r5ehkLooyONnGFgWZu5Wmhj/4DepYwbDcA8/3eFfNTWbXhGpzXbFy82Eiy/WOsmvxyJSjJWXnarxrI3Vs3cGBGPLM68kUWgszcqJ+AodDIYwisw2Tbd6Q7WW7Gk6SDvxwh3zChMvs335KZYTxjnbhJ/KDXky0nplOYzpdrK2Gf28s4ETDBjGbHnLm1FGv5xdKWFgpKMGWDnv9vYHr28KOOgLA5NvVCb42VbbLb1p7Ac/D7v3LNulRdH/la7ZARirS6+wbaJAy0/Ja4wt8eGinBDJG83ZQ//cv1/UE4wx0ohFYAjJrmEELLtNdwmCRFa7N7uCU+XVTE665LkjADoP2HEA6yihX8niDh/MMyOl5OBsMkBeaPD6PF8oI00j6mtfHAf3axAR6jcsUPimNJ4NfT5rvjLBe1SMtdr8B89qPHb1a/ATrTo+q5E+rxxYVf62yk9G2zEmtsfXIUCjzUcYYJRs7khk8EN0Nx7SJTvrsTotAQchZC6NWCdUMvKrHlUdfaizxycSjJEAV+DRZOioramJGcYHUA07Pn1FQ6iWfHnLj0LGnH8mC6NRa+QFTXeMydT3pBoNmqC3fZ56OgJQYNJH6JPuxYpas=
      - secure: usIjyFhHnN3LzLbSvmlaFSMbRb++76hE5xVnUlVX0x0eUA3QEqlipAYX/hMHUy+O6zFaK/Ny30LvkP63KGddZKo378mXXYN+befvf2dULnGyvSYmzG+8zP3i9eB8wG5MVMFHPrEHsTp9qSxVL2VVoZ2+9/zH6+DbGi/Q7F4jC1JMteVYjdAhAZZwn1sBpr6SIF+EL2f+QvoJCc9cOL5XfmoLCbZxEzw5Zcx3hE7badj7R5pDNjtERliqSEH47tfxLq9emFLSqcHpxt6UAj8EhnP2jvNRITVhLlMmZCpdTZkqlHAXBD7TASQJrFguPtpeN4Jm0lAd9bPrqDKF8IGM/75rksZdq9tAYtEMMHpqEw1ORAZqjueJCMD009pcxhqeucFTxulAzTPs8h+o8AhiDZMyDyohRxjkmkY/Ngt8o//omyaZEQpNS0AFXf4bu2iGX7uqDYNfCAKbYhuhuKNs6Lp9bUAFJUNO6ZkyPRkPpuyAuIqvaDaX+OdUGjqwJVtJz8ctqHh5np7zbai0lDQ/k2jsDD0gOhPFRxkGKfTGYiHrusFH/d/oKHlm6+3/nDNDUAl32uX5mr7BKv/IEr7lONoTtrb6Mke1rK/IUofe0igTx8vPPCTBkzWjn/UMtsKYUF+XQhCy63/5FdGWLT9qM3+QRHR7h7ouWINumRF3ZNY=
