sudo: required
language: java
jdk:
- openjdk11
before_install:
- openssl aes-256-cbc -K $encrypted_033a38c09167_key -iv $encrypted_033a38c09167_iv
  -in travis/codesigning.asc.enc -out travis/codesigning.asc -d
- gpg --fast-import travis/codesigning.asc
- openssl aes-256-cbc -K $encrypted_033a38c09167_key -iv $encrypted_033a38c09167_iv
  -in travis/helseci.key.enc -out travis/helseci.key -d
- git clone https://github.com/navikt/github-apps-support.git
- export PATH=`pwd`/github-apps-support/bin:$PATH
- export GH_TOKEN=$(generate-installation-token.sh `generate-jwt.sh ./travis/helseci.key
  $GITHUB_APP_ID`)
- export COMMIT_SHORT=$(git rev-parse --short HEAD)
- export ORIGINAL_COMMITTER=$(git log -1 --pretty=format:'%an <%ae>')
- echo -e "machine github.com\n  login $GH_TOKEN" > ~/.netrc
- rm "${JAVA_HOME}/lib/security/cacerts"
- ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
script:
- awk '($1=="version" && $3 ~ /[0-9]+/){$3=$3+1} 1' build.gradle.kts > build.gradle.new
  && mv build.gradle.new build.gradle.kts
- "./gradlew check"
- "./gradlew build"
- |
  if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then

    git config user.name team-helse[bot]
    git config user.email team-helse[bot]@users.noreply.github.com

    git add build.gradle.kts
    git commit -m "Bump version [skip ci]" -m "Caused by $TRAVIS_BUILD_WEB_URL" --author "$ORIGINAL_COMMITTER"

   ./gradlew publish --info closeAndReleaseRepository

    git push https://x-access-token:$GH_TOKEN@github.com/navikt/helse-streams.git HEAD:master
  fi
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
env:
  global:
  - GITHUB_APP_ID=19726
  - GPG_KEY_NAME=navikt
  - OSSRH_JIRA_USERNAME=navikt
  - secure: NlEjxSNoaD4omOnA+zU6uO38tJQhTw++CjDc42EYRdaLckM12wz/qPFnPuha3bS5qNHH68CjblykTuiv2rDWxFcH6AMannLGdDZcsAvPBVX3QCN3Mz7YLny+0fmbKma6+cmgDOCU3uDg9cKdeHpfu7OuZgTtu4J/Y28lzLq/tefK2UPRk6kbyqC06v1DeoAd3YyJ5IzhXaVy0uIsSMkL3zgL5UXBdNJs4ZNcwM6MaqPtlMO97I+OvPmpNoomHkVVz7nrSNs9YaTE8119A/jZAebWeGzyMgnUAMInd0XSbEX7lplWxURS/CUXX4Hmj52/blJ3iy2OHvCWrapgXhaTxTGQVntJbsWb9NpSMATWUYiJJPVjVcDv4wDLRBAOmqeJiBFkyxl3clI0GT3ED3qMQfwNYqvkox8XyaafJkYS8It4BdxetX3zW6vD46Wtgf/YDEv7gt489hKgQaK2o/hKafuXjLFAXhKhohRCaJJEcsguvXP3MVVX7kmrdSTTV7T+7CKjZGuEdoX4npklWXQGj1B5zKgQ+d0vLfgoj2o93h1+ZC+Ht2+YenbW9+lOYckFhe3q2P0OAPXi5k3UX8ehK7blz5c9fFIN0CsQpoXlHbXKbER83fxUTmYiojT0+ves//+Qa3EUeiYYyTHg6vl7/muHPjew6mcU6l+mRVM1bv0=
  - secure: Vr7MB0Jk0RzUFOilz/fKcVhX55bIa8JpXTZCmvAQU/Gw5UfiRYas70hpFju+ru1lAadZw3Ln447JxzwBjbumScfBg2cMF7xddqNOOXOwl4Lo96zSpBVqRHEWYWCzGoJMV/6QI+ZCoOrH+yCaAVZhmgPXyBFa5CaV710ddznTq1ZhifYCcjRgR7yx1xV2Y3cqpnqFzOSAZGSl3hA/RHuXfM5UyNzWP8Kw1dbgTC+pwk7771gD57oZltRzeU//xADpwzpWPdQiPriwV7uGdloWSCMlsp0WQY23beJ+Jt0ZH0Z+atdyNXnBHQjIqk8T/NZTqPlRuyz4TQH5tfobAHWYhLvEEc9A8LXupXVD6A/+Yt0xDTY5zUAJlSIiJuHkMEkptf2EWoDF51If+rC0zae6P2kSlYsuIijr5Ft3nWhdIW6h0ljMgswAHr1h8XE/AiWsBP6c3zuiH+v+RUvvo7UqbB7vHwZIV69heYI7Y9pleCR8OsgqLNTsSEE9SN7wuEKKBFAhiKzoFFMvqoLt3NJe97PQnYeX6W3z80d/2JHpBenYbKP10eBOMC334QUK549V8wxCIst5cOyS5KmtyRE+4Yfdgq2+m83Hh/sFARHk+r6kXOuluYPHYosMGKRAlXUdDIujN2VwWYjyMHDY5oQA8TlMUoYZ48Ypw4HUzhIKEbs=
  - secure: mjrq1B67N4mC8fVLYcmuytyvmXC2LOgsk6Z1NmqBfKapdeVGUshtIx3eVaLwseiylEfT38TESOgn5viVECHRfq/1SX4+HDyPivd6bZq06zvTsqhjaXkgZB/nDoazbNrytg30mwl9pRMcQxlQsInM4OG/nud7lQB4YWtnSJs9fZX10lYNhkMZC8pS4KAg8DNCH1OY2OfC81Fm4P+oFd0TP+xGOmYbcl8yexriFytAyVXpnOxNrq/jyHOYvM6fuX7VE1TwN6khtFOqOyCsaeDmNLYrMlPsgX1FmzyGdEUp/216Pf49I8ykHsgU1leuQauQGnmu+BPm/8numQ6OkAp3yPP+HAJYWGn4yINjJQIES4H9YJ9Uclk1Unc2nqn93DfVWUUSw3abp1cGsweyskK1+A9GGtisxkbxyd3pYlSr2+dO9yqgTaWblu7wwT6ORpb4xkMzKty67XrgcZquXA/5q6NmJOFNrOF6RnMTPrJSTNqC9ec8SpAHW6KTJYJ63vjm1iO1YMltya9RLfngSbpsI94kyEJa+hwh2sEFPUnuOK0vs/21texfyJmQOjJoHrRppDZX1szBy8ORfBtHC+B3MzoiVHtya01L3rGtENRsPN54Lge/ZnV6BO5Mu8/S91/KJO76RuYkhOibJ4kS3/rNou3hpJszqaUq3gtWss27m/I=
  - secure: PqABRk2zQUUgbd+ATmj/Z0LRQdT5dnzj74PBIJRpoP5Qk/UJfTtZhsgGaIcTfN6Y1e4ut/E3+NMD6ADOWjkfao8HkW/w/tdkmAyKRQzcvvQc7wPg9kBByfZ3mdYHx/EZDqk2VIEFmA6hRmJW6dc09gymX1tfMfnOThM7N8E6r8+P5OO4diERnId1FCc4BfhDAZgBdWLveDpjVh67VxNT/ca9oasGeJOdlScTJpLQM5ZkkZYr8ahALjmvN4g3mg3KBow01l9Q3RAiv4bPP9RsuRFn6dZPvvaeIGsn9QjhNsw+qGOPgyhBES5jxqxOaWBfaOZH58ztqb3aNJhO1tEJ3TdMu59iYzj0XpernzX/M84M0rlbSe51Nh1QNAuKaN4UdwdqnjMJ0LO193iesFhzrYWaptfXShUrr94agfUSnZUR8Qlcy1NSOqz2o0vy6mj+t8QDsHTXLxoB/99GICUAH8bP1q6RTbqpusGd2+XIHLE7smMaZC3kjQ8sQtZ6GDUtNso96CfR+7URfa9hifeK6+x3x9NW1eVT1EO2ewwOMktJojwNmuWe+mRnerDkJ45F+bqVNxsvsSc2spJ6ncFI8rHAgEXdfVAmDyfG4dGHlSK6G6gVJDem1rpxkNyXzq6PKFbY+uJeD/7NeZFTmrr18ctxlPdme5aVO6JrY1RjSFc=
