name: Bygg og deploy

on:
   push:
      branches:
         - master

jobs:
   build:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v1
         - uses: actions/setup-java@v1
           with:
              java-version: '11.x'
         - name: create version number
           run: |
              echo $(echo $GITHUB_SHA | cut -c1-7) > .version
         - name: test and build
           run: ./mvnw clean install
         - name: set version
           run: ./mvnw versions:set -DnewVersion="$(cat .version)"
         - name: upload artifact
           run: ./mvnw --settings settings.xml deploy -X -DskipTests=true
           env:
              GITHUB_USERNAME: x-access-token
              GITHUB_PASSWORD: ${{ secrets.GITHUB_ACCESS_TOKEN }}
